# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_MEM_J = 2048
VAGRANT_CPUS_J = 2
VAGRANT_MEM_GL = 4096
VAGRANT_CPUS_GL = 2

Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "geerlingguy/centos7"
    jenkins.vm.network :private_network, ip: "10.0.5.10"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins"
      vb.memory = VAGRANT_MEM_J
      vb.cpus = VAGRANT_CPUS_J
    end
    jenkins.vm.provision :shell do |shell|
      shell.path = "jenkins_install.sh"
    end
  end

  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.box = "generic/debian9"
    gitlab.vm.network :private_network, ip: "10.0.5.11"
    gitlab.vm.hostname = "gitlab"
    gitlab.vm.provider "virtualbox" do |vb|
      vb.name = "gitlab"
      vb.memory = VAGRANT_MEM_GL
      vb.cpus = VAGRANT_CPUS_GL
    end
    gitlab.vm.provision :shell do |shell|
      shell.path = "gitlab_install.sh"
    end
  end
end
