# -*- mode: ruby -*-
# vi: set ft=ruby :

cluster = {
  "lb" => { :ip => "10.0.0.10", :cpus => 1, :mem => 1024},
  "web1" => { :ip => "10.0.0.11", :cpus => 1, :mem => 1024},
  "web2" => { :ip => "10.0.0.12", :cpus => 1, :mem => 1024}
}

Vagrant.configure("2") do |config|
  cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "ubuntu/xenial64"
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.memory = info[:mem]
        vb.cpus = info[:cpus]
      end
    end
  end
end
