# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_MEM_VM = 1024
VAGRANT_CPUS_VM = 1

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network :private_network, ip:"10.0.0.10" 
  config.vm.provider "virtualbox" do |vb|
    vb.memory = VAGRANT_MEM_VM
    vb.cpus = VAGRANT_CPUS_VM
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "nginx.yaml"
    ansible.install = true
    ansible.install_mode = "pip"
    ansible.pip_install_cmd = "curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | sudo python"
  end
end
