# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_MEM_VM = 2048
VAGRANT_CPUS_VM = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.network "private_network", ip: "10.0.0.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = VAGRANT_MEM_VM
    vb.cpus = VAGRANT_CPUS_VM
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
    sudo service ssh restart
  SHELL
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y -qq nginx
    sudo systemctl start nginx
  SHELL
end
