# -*- mode: ruby -*-
# vi: set ft=ruby :

cluster = {
  "lb" => {
    :ip => "10.0.0.10",
    :cpus => 1,
    :mem => 1024  ,
    :shell => "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/lb.sh",
  },
  "web1" => {
    :ip => "10.0.0.11",
    :cpus => 1,
    :mem => 1024,
    :shell => "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/web.sh",
    :shellargs => [" 1"]
  }, 
  "web2" => {
    :ip => "10.0.0.12",
    :cpus => 1,
    :mem => 1024,
    :shell => "https://raw.githubusercontent.com/PacktPublishing/Hands-On-DevOps-with-Vagrant/master/Chapter07/web.sh",
    :shellargs => [" 2"]
  }
}

Vagrant.configure("2") do |config|
  cluster.each do |hostname, info|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "ubuntu/xenial64"
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.memory = info[:mem]
        vb.cpus = info[:cpus]
      end
      cfg.vm.provision :shell do |shell|
        shell.path = info[:shell]
        if info.has_key?(:shellargs)
          shell.args = info[:shellargs]
        end
      end
    end
  end
end
