# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_MEM_VM = 2048
VAGRANT_CPUS_VM = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = VAGRANT_MEM_VM
    vb.cpus = VAGRANT_CPUS_VM
  end
end
